#A3vFkGBrj4MRugemEXWdSFztWgBXi9eQPtD3V28Va7WH：
尽管我们设置了daily_trader > 50的过滤条件去过滤做市商和高频机器人，但是他还是在最终的list里，所以我们可能需要拓展交易池，因为我们现在只在搜索一个交易池，这个人可能在我们这个交易池的交易量没达到过滤条件但是在其他交易池的交易量很大，所以我们需要搜索更多的交易池，来看看这个人在其他交易池的交易量情况，如果在其他交易池的交易量也很大，那么我们就可以确定这个人是一个真正的交易者，而不是一个做市商或者高频机器人。

#99mRw3EzdJZWEUjgp1nrU4WeHsukUBjbh7gYE7pm4F3c
同上

#HkAop6zTAB933j7nhhUSGwLL5eKZyQizcZsgiL1MjMq1
同上

#3dozCLAkkP2crzAggABNwFejj2LjAAFJSpDkVDDoBWwu
同上
#o721riuQGZKmbeb5DHUyX6x7bVLArUKuWpdSBxGBgfM
同上